server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Hỗ trợ React Router (Single Page Application)
        # Nginx sẽ tự động redirect về index.html nếu không tìm thấy file cụ thể
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
